"""Add categories, sub-translations, and analytics models

Revision ID: 429159612ffc
Revises: 706928162f9f
Create Date: 2025-10-02 02:26:08.222472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '429159612ffc'
down_revision: Union[str, Sequence[str], None] = '706928162f9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=False)
    op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=True)
    op.create_table('category_analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('total_contributions', sa.Integer(), nullable=False),
    sa.Column('approved_contributions', sa.Integer(), nullable=False),
    sa.Column('total_sub_translations', sa.Integer(), nullable=False),
    sa.Column('unique_contributors', sa.Integer(), nullable=False),
    sa.Column('average_quality_score', sa.Float(), nullable=False),
    sa.Column('last_contribution_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_analytics_id'), 'category_analytics', ['id'], unique=False)
    op.create_table('user_analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('total_contributions', sa.Integer(), nullable=False),
    sa.Column('approved_contributions', sa.Integer(), nullable=False),
    sa.Column('rejected_contributions', sa.Integer(), nullable=False),
    sa.Column('total_sub_translations', sa.Integer(), nullable=False),
    sa.Column('total_words_contributed', sa.Integer(), nullable=False),
    sa.Column('average_approval_rate', sa.Float(), nullable=False),
    sa.Column('streak_days', sa.Integer(), nullable=False),
    sa.Column('last_contribution_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_analytics_id'), 'user_analytics', ['id'], unique=False)
    op.create_table('analytics_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('CONTRIBUTION_CREATED', 'CONTRIBUTION_APPROVED', 'CONTRIBUTION_REJECTED', 'SUB_TRANSLATION_CREATED', 'EXPORT_REQUESTED', 'CATEGORY_ASSIGNED', 'USER_LOGIN', 'USER_REGISTERED', name='analyticseventtype'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('contribution_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('event_metadata', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['contribution_id'], ['contributions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_events_event_type'), 'analytics_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_analytics_events_id'), 'analytics_events', ['id'], unique=False)
    op.create_index(op.f('ix_analytics_events_timestamp'), 'analytics_events', ['timestamp'], unique=False)
    op.create_table('contribution_categories',
    sa.Column('contribution_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['contribution_id'], ['contributions.id'], ),
    sa.PrimaryKeyConstraint('contribution_id', 'category_id')
    )
    op.create_table('sub_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_contribution_id', sa.Integer(), nullable=False),
    sa.Column('source_word', sa.String(length=200), nullable=False),
    sa.Column('target_word', sa.String(length=200), nullable=False),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('word_position', sa.Integer(), nullable=False),
    sa.Column('difficulty_level', sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', name='difficultylevel'), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_contribution_id'], ['contributions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sub_translations_id'), 'sub_translations', ['id'], unique=False)
    op.create_index(op.f('ix_sub_translations_source_word'), 'sub_translations', ['source_word'], unique=False)
    op.create_index(op.f('ix_sub_translations_target_word'), 'sub_translations', ['target_word'], unique=False)
    op.add_column('contributions', sa.Column('difficulty_level', sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', name='difficultylevel'), nullable=True))
    op.add_column('contributions', sa.Column('context_notes', sa.Text(), nullable=True))
    op.add_column('contributions', sa.Column('cultural_notes', sa.Text(), nullable=True))
    op.add_column('contributions', sa.Column('pronunciation_guide', sa.String(length=500), nullable=True))
    op.add_column('contributions', sa.Column('usage_examples', sa.Text(), nullable=True))
    op.add_column('contributions', sa.Column('quality_score', sa.Float(), nullable=True))
    op.add_column('contributions', sa.Column('is_phrase', sa.Boolean(), nullable=True))
    op.add_column('contributions', sa.Column('has_sub_translations', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('display_name', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('google_id', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('avatar_url', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('bio', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False, server_default='1'))
    op.add_column('users', sa.Column('is_email_verified', sa.Boolean(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('last_login', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_column('users', 'last_login')
    op.drop_column('users', 'is_email_verified')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'bio')
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'google_id')
    op.drop_column('users', 'display_name')
    op.drop_column('contributions', 'has_sub_translations')
    op.drop_column('contributions', 'is_phrase')
    op.drop_column('contributions', 'quality_score')
    op.drop_column('contributions', 'usage_examples')
    op.drop_column('contributions', 'pronunciation_guide')
    op.drop_column('contributions', 'cultural_notes')
    op.drop_column('contributions', 'context_notes')
    op.drop_column('contributions', 'difficulty_level')
    op.drop_index(op.f('ix_sub_translations_target_word'), table_name='sub_translations')
    op.drop_index(op.f('ix_sub_translations_source_word'), table_name='sub_translations')
    op.drop_index(op.f('ix_sub_translations_id'), table_name='sub_translations')
    op.drop_table('sub_translations')
    op.drop_table('contribution_categories')
    op.drop_index(op.f('ix_analytics_events_timestamp'), table_name='analytics_events')
    op.drop_index(op.f('ix_analytics_events_id'), table_name='analytics_events')
    op.drop_index(op.f('ix_analytics_events_event_type'), table_name='analytics_events')
    op.drop_table('analytics_events')
    op.drop_index(op.f('ix_user_analytics_id'), table_name='user_analytics')
    op.drop_table('user_analytics')
    op.drop_index(op.f('ix_category_analytics_id'), table_name='category_analytics')
    op.drop_table('category_analytics')
    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
