"""Add comprehensive analytics models

Revision ID: a75278c496f6
Revises: 4f9a97ff4219
Create Date: 2025-10-02 18:38:21.697452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a75278c496f6'
down_revision: Union[str, Sequence[str], None] = '4f9a97ff4219'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_metrics_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_users', sa.Integer(), nullable=False),
    sa.Column('active_users_today', sa.Integer(), nullable=False),
    sa.Column('new_registrations', sa.Integer(), nullable=False),
    sa.Column('total_contributions', sa.Integer(), nullable=False),
    sa.Column('contributions_today', sa.Integer(), nullable=False),
    sa.Column('contributions_approved_today', sa.Integer(), nullable=False),
    sa.Column('contributions_rejected_today', sa.Integer(), nullable=False),
    sa.Column('average_quality_score', sa.Float(), nullable=True),
    sa.Column('approval_rate_today', sa.Float(), nullable=True),
    sa.Column('average_response_time_ms', sa.Float(), nullable=True),
    sa.Column('api_calls_today', sa.Integer(), nullable=False),
    sa.Column('export_requests_today', sa.Integer(), nullable=False),
    sa.Column('total_vocabulary_items', sa.Integer(), nullable=False),
    sa.Column('total_verb_forms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_metrics_snapshots_date'), 'daily_metrics_snapshots', ['date'], unique=True)
    op.create_index(op.f('ix_daily_metrics_snapshots_id'), 'daily_metrics_snapshots', ['id'], unique=False)
    op.create_table('system_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.Column('metric_unit', sa.String(length=20), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('granularity', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_metrics_category'), 'system_metrics', ['category'], unique=False)
    op.create_index(op.f('ix_system_metrics_granularity'), 'system_metrics', ['granularity'], unique=False)
    op.create_index(op.f('ix_system_metrics_id'), 'system_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_system_metrics_metric_name'), 'system_metrics', ['metric_name'], unique=False)
    op.create_index(op.f('ix_system_metrics_period_end'), 'system_metrics', ['period_end'], unique=False)
    op.create_index(op.f('ix_system_metrics_period_start'), 'system_metrics', ['period_start'], unique=False)
    op.create_table('language_learning_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('verb_forms_practiced', sa.Integer(), nullable=False),
    sa.Column('noun_classes_practiced', sa.Integer(), nullable=False),
    sa.Column('vocabulary_items_learned', sa.Integer(), nullable=False),
    sa.Column('pronunciation_attempts', sa.Integer(), nullable=False),
    sa.Column('beginner_completions', sa.Integer(), nullable=False),
    sa.Column('intermediate_completions', sa.Integer(), nullable=False),
    sa.Column('advanced_completions', sa.Integer(), nullable=False),
    sa.Column('average_accuracy', sa.Float(), nullable=True),
    sa.Column('improvement_rate', sa.Float(), nullable=True),
    sa.Column('favorite_category', sa.String(length=50), nullable=True),
    sa.Column('weakest_area', sa.String(length=50), nullable=True),
    sa.Column('total_study_time_minutes', sa.Integer(), nullable=False),
    sa.Column('last_study_session', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_language_learning_metrics_id'), 'language_learning_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_language_learning_metrics_user_id'), 'language_learning_metrics', ['user_id'], unique=False)
    op.create_table('user_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('activity_type', sa.String(length=50), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('activity_metadata', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_activities_activity_type'), 'user_activities', ['activity_type'], unique=False)
    op.create_index(op.f('ix_user_activities_created_at'), 'user_activities', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_activities_id'), 'user_activities', ['id'], unique=False)
    op.create_index(op.f('ix_user_activities_resource_id'), 'user_activities', ['resource_id'], unique=False)
    op.create_index(op.f('ix_user_activities_resource_type'), 'user_activities', ['resource_type'], unique=False)
    op.create_index(op.f('ix_user_activities_session_id'), 'user_activities', ['session_id'], unique=False)
    op.create_index(op.f('ix_user_activities_user_id'), 'user_activities', ['user_id'], unique=False)
    op.create_table('user_engagement_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('login_count', sa.Integer(), nullable=False),
    sa.Column('session_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('contributions_submitted', sa.Integer(), nullable=False),
    sa.Column('contributions_approved', sa.Integer(), nullable=False),
    sa.Column('contributions_rejected', sa.Integer(), nullable=False),
    sa.Column('reviews_performed', sa.Integer(), nullable=False),
    sa.Column('average_quality_score', sa.Float(), nullable=True),
    sa.Column('approval_rate', sa.Float(), nullable=True),
    sa.Column('consecutive_days_active', sa.Integer(), nullable=False),
    sa.Column('longest_streak_days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_engagement_metrics_id'), 'user_engagement_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_user_engagement_metrics_period_end'), 'user_engagement_metrics', ['period_end'], unique=False)
    op.create_index(op.f('ix_user_engagement_metrics_period_start'), 'user_engagement_metrics', ['period_start'], unique=False)
    op.create_index(op.f('ix_user_engagement_metrics_user_id'), 'user_engagement_metrics', ['user_id'], unique=False)
    op.create_table('contribution_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contribution_id', sa.Integer(), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('complexity_score', sa.Float(), nullable=True),
    sa.Column('similarity_score', sa.Float(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('approval_time_minutes', sa.Integer(), nullable=True),
    sa.Column('nlp_processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('qa_issues_count', sa.Integer(), nullable=False),
    sa.Column('qa_warnings_count', sa.Integer(), nullable=False),
    sa.Column('source_word_count', sa.Integer(), nullable=True),
    sa.Column('target_word_count', sa.Integer(), nullable=True),
    sa.Column('character_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['contribution_id'], ['contributions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contribution_metrics_contribution_id'), 'contribution_metrics', ['contribution_id'], unique=True)
    op.create_index(op.f('ix_contribution_metrics_id'), 'contribution_metrics', ['id'], unique=False)
    op.drop_index('ix_analytics_timestamp_desc', table_name='analytics_events')
    op.drop_index('ix_analytics_type_time_user', table_name='analytics_events')
    op.drop_index('ix_categories_parent_active_sort', table_name='categories')
    op.drop_index('ix_contrib_cat_category_id', table_name='contribution_categories')
    op.drop_index('ix_contrib_cat_contrib_id', table_name='contribution_categories')
    op.drop_index('ix_contributions_difficulty_status', table_name='contributions')
    op.drop_index('ix_contributions_source_target_text', table_name='contributions')
    op.drop_index('ix_contributions_status_created_quality', table_name='contributions')
    op.alter_column('morphological_submissions', 'morphological_data',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=False)
    op.drop_index('ix_morphological_submissions_status', table_name='morphological_submissions')
    op.create_index(op.f('ix_morphological_submissions_id'), 'morphological_submissions', ['id'], unique=False)
    op.drop_index('ix_subtrans_contrib_position', table_name='sub_translations')
    op.drop_index('ix_subtrans_source_target', table_name='sub_translations')
    op.drop_index('ix_user_analytics_contributions', table_name='user_analytics')
    op.alter_column('verb_conjugations', 'tense',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('PRESENT', 'PAST', 'FUTURE', 'HABITUAL', name='tensetype'),
               existing_nullable=False)
    op.alter_column('verb_conjugations', 'aspect',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('SIMPLE', 'CONTINUOUS', 'PERFECT', 'PERFECT_CONTINUOUS', name='aspecttype'),
               existing_nullable=False)
    op.alter_column('verb_conjugations', 'mood',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('INDICATIVE', 'IMPERATIVE', 'SUBJUNCTIVE', 'CONDITIONAL', name='moodtype'),
               existing_nullable=False)
    op.alter_column('verb_conjugations', 'polarity',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('AFFIRMATIVE', 'NEGATIVE', name='polaritytype'),
               existing_nullable=False)
    op.alter_column('verb_conjugations', 'person',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('FIRST', 'SECOND', 'THIRD', name='persontype'),
               existing_nullable=False)
    op.alter_column('verb_conjugations', 'number',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('SINGULAR', 'PLURAL', name='numbertype'),
               existing_nullable=False)
    op.alter_column('verb_conjugations', 'morphological_breakdown',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index('ix_verb_conjugations_verb_id', table_name='verb_conjugations')
    op.create_index(op.f('ix_verb_conjugations_aspect'), 'verb_conjugations', ['aspect'], unique=False)
    op.create_index(op.f('ix_verb_conjugations_id'), 'verb_conjugations', ['id'], unique=False)
    op.create_index(op.f('ix_verb_conjugations_mood'), 'verb_conjugations', ['mood'], unique=False)
    op.create_index(op.f('ix_verb_conjugations_number'), 'verb_conjugations', ['number'], unique=False)
    op.create_index(op.f('ix_verb_conjugations_person'), 'verb_conjugations', ['person'], unique=False)
    op.create_index(op.f('ix_verb_conjugations_polarity'), 'verb_conjugations', ['polarity'], unique=False)
    op.create_index(op.f('ix_verb_conjugations_tense'), 'verb_conjugations', ['tense'], unique=False)
    op.drop_index('ix_verbs_base_form', table_name='verbs')
    op.create_index(op.f('ix_verbs_base_form'), 'verbs', ['base_form'], unique=True)
    op.create_index(op.f('ix_verbs_id'), 'verbs', ['id'], unique=False)
    op.alter_column('word_classes', 'word_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('NOUN', 'VERB', 'ADJECTIVE', 'ADVERB', 'PRONOUN', 'PREPOSITION', 'CONJUNCTION', 'INTERJECTION', name='wordtype'),
               existing_nullable=False)
    op.alter_column('word_classes', 'examples',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.create_index(op.f('ix_word_classes_id'), 'word_classes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_word_classes_id'), table_name='word_classes')
    op.alter_column('word_classes', 'examples',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('word_classes', 'word_type',
               existing_type=sa.Enum('NOUN', 'VERB', 'ADJECTIVE', 'ADVERB', 'PRONOUN', 'PREPOSITION', 'CONJUNCTION', 'INTERJECTION', name='wordtype'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_index(op.f('ix_verbs_id'), table_name='verbs')
    op.drop_index(op.f('ix_verbs_base_form'), table_name='verbs')
    op.create_index('ix_verbs_base_form', 'verbs', ['base_form'], unique=False)
    op.drop_index(op.f('ix_verb_conjugations_tense'), table_name='verb_conjugations')
    op.drop_index(op.f('ix_verb_conjugations_polarity'), table_name='verb_conjugations')
    op.drop_index(op.f('ix_verb_conjugations_person'), table_name='verb_conjugations')
    op.drop_index(op.f('ix_verb_conjugations_number'), table_name='verb_conjugations')
    op.drop_index(op.f('ix_verb_conjugations_mood'), table_name='verb_conjugations')
    op.drop_index(op.f('ix_verb_conjugations_id'), table_name='verb_conjugations')
    op.drop_index(op.f('ix_verb_conjugations_aspect'), table_name='verb_conjugations')
    op.create_index('ix_verb_conjugations_verb_id', 'verb_conjugations', ['verb_id'], unique=False)
    op.alter_column('verb_conjugations', 'morphological_breakdown',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('verb_conjugations', 'number',
               existing_type=sa.Enum('SINGULAR', 'PLURAL', name='numbertype'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('verb_conjugations', 'person',
               existing_type=sa.Enum('FIRST', 'SECOND', 'THIRD', name='persontype'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('verb_conjugations', 'polarity',
               existing_type=sa.Enum('AFFIRMATIVE', 'NEGATIVE', name='polaritytype'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('verb_conjugations', 'mood',
               existing_type=sa.Enum('INDICATIVE', 'IMPERATIVE', 'SUBJUNCTIVE', 'CONDITIONAL', name='moodtype'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('verb_conjugations', 'aspect',
               existing_type=sa.Enum('SIMPLE', 'CONTINUOUS', 'PERFECT', 'PERFECT_CONTINUOUS', name='aspecttype'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('verb_conjugations', 'tense',
               existing_type=sa.Enum('PRESENT', 'PAST', 'FUTURE', 'HABITUAL', name='tensetype'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.create_index('ix_user_analytics_contributions', 'user_analytics', ['total_contributions', 'approved_contributions'], unique=False)
    op.create_index('ix_subtrans_source_target', 'sub_translations', ['source_word', 'target_word'], unique=False)
    op.create_index('ix_subtrans_contrib_position', 'sub_translations', ['parent_contribution_id', 'word_position'], unique=False)
    op.drop_index(op.f('ix_morphological_submissions_id'), table_name='morphological_submissions')
    op.create_index('ix_morphological_submissions_status', 'morphological_submissions', ['status'], unique=False)
    op.alter_column('morphological_submissions', 'morphological_data',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_index('ix_contributions_status_created_quality', 'contributions', ['status', 'created_at', 'quality_score'], unique=False)
    op.create_index('ix_contributions_source_target_text', 'contributions', ['source_text', 'target_text'], unique=False)
    op.create_index('ix_contributions_difficulty_status', 'contributions', ['difficulty_level', 'status'], unique=False)
    op.create_index('ix_contrib_cat_contrib_id', 'contribution_categories', ['contribution_id'], unique=False)
    op.create_index('ix_contrib_cat_category_id', 'contribution_categories', ['category_id'], unique=False)
    op.create_index('ix_categories_parent_active_sort', 'categories', ['parent_id', 'is_active', 'sort_order'], unique=False)
    op.create_index('ix_analytics_type_time_user', 'analytics_events', ['event_type', 'timestamp', 'user_id'], unique=False)
    op.create_index('ix_analytics_timestamp_desc', 'analytics_events', ['timestamp'], unique=False)
    op.drop_index(op.f('ix_contribution_metrics_id'), table_name='contribution_metrics')
    op.drop_index(op.f('ix_contribution_metrics_contribution_id'), table_name='contribution_metrics')
    op.drop_table('contribution_metrics')
    op.drop_index(op.f('ix_user_engagement_metrics_user_id'), table_name='user_engagement_metrics')
    op.drop_index(op.f('ix_user_engagement_metrics_period_start'), table_name='user_engagement_metrics')
    op.drop_index(op.f('ix_user_engagement_metrics_period_end'), table_name='user_engagement_metrics')
    op.drop_index(op.f('ix_user_engagement_metrics_id'), table_name='user_engagement_metrics')
    op.drop_table('user_engagement_metrics')
    op.drop_index(op.f('ix_user_activities_user_id'), table_name='user_activities')
    op.drop_index(op.f('ix_user_activities_session_id'), table_name='user_activities')
    op.drop_index(op.f('ix_user_activities_resource_type'), table_name='user_activities')
    op.drop_index(op.f('ix_user_activities_resource_id'), table_name='user_activities')
    op.drop_index(op.f('ix_user_activities_id'), table_name='user_activities')
    op.drop_index(op.f('ix_user_activities_created_at'), table_name='user_activities')
    op.drop_index(op.f('ix_user_activities_activity_type'), table_name='user_activities')
    op.drop_table('user_activities')
    op.drop_index(op.f('ix_language_learning_metrics_user_id'), table_name='language_learning_metrics')
    op.drop_index(op.f('ix_language_learning_metrics_id'), table_name='language_learning_metrics')
    op.drop_table('language_learning_metrics')
    op.drop_index(op.f('ix_system_metrics_period_start'), table_name='system_metrics')
    op.drop_index(op.f('ix_system_metrics_period_end'), table_name='system_metrics')
    op.drop_index(op.f('ix_system_metrics_metric_name'), table_name='system_metrics')
    op.drop_index(op.f('ix_system_metrics_id'), table_name='system_metrics')
    op.drop_index(op.f('ix_system_metrics_granularity'), table_name='system_metrics')
    op.drop_index(op.f('ix_system_metrics_category'), table_name='system_metrics')
    op.drop_table('system_metrics')
    op.drop_index(op.f('ix_daily_metrics_snapshots_id'), table_name='daily_metrics_snapshots')
    op.drop_index(op.f('ix_daily_metrics_snapshots_date'), table_name='daily_metrics_snapshots')
    op.drop_table('daily_metrics_snapshots')
    # ### end Alembic commands ###
